// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: push-service.proto

package pushservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IPv4Addresses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ipv4Address []string `protobuf:"bytes,1,rep,name=ipv4address,proto3" json:"ipv4address,omitempty"`
}

func (x *IPv4Addresses) Reset() {
	*x = IPv4Addresses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPv4Addresses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPv4Addresses) ProtoMessage() {}

func (x *IPv4Addresses) ProtoReflect() protoreflect.Message {
	mi := &file_push_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPv4Addresses.ProtoReflect.Descriptor instead.
func (*IPv4Addresses) Descriptor() ([]byte, []int) {
	return file_push_service_proto_rawDescGZIP(), []int{0}
}

func (x *IPv4Addresses) GetIpv4Address() []string {
	if x != nil {
		return x.Ipv4Address
	}
	return nil
}

type DataRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataRate    int64  `protobuf:"varint,1,opt,name=dataRate,proto3" json:"dataRate,omitempty"`
	Ipv4Address string `protobuf:"bytes,2,opt,name=ipv4address,proto3" json:"ipv4address,omitempty"`
}

func (x *DataRate) Reset() {
	*x = DataRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRate) ProtoMessage() {}

func (x *DataRate) ProtoReflect() protoreflect.Message {
	mi := &file_push_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRate.ProtoReflect.Descriptor instead.
func (*DataRate) Descriptor() ([]byte, []int) {
	return file_push_service_proto_rawDescGZIP(), []int{1}
}

func (x *DataRate) GetDataRate() int64 {
	if x != nil {
		return x.DataRate
	}
	return 0
}

func (x *DataRate) GetIpv4Address() string {
	if x != nil {
		return x.Ipv4Address
	}
	return ""
}

var File_push_service_proto protoreflect.FileDescriptor

var file_push_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x75, 0x73, 0x68, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x75, 0x73, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x22, 0x31, 0x0a, 0x0d, 0x49, 0x50, 0x76, 0x34, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x70, 0x76, 0x34, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x70, 0x76, 0x34, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x48, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x52, 0x61, 0x74, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x52, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x52, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x69, 0x70, 0x76, 0x34, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x69, 0x70, 0x76, 0x34, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x5c,
	0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a,
	0x14, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x49, 0x50, 0x76, 0x34, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x1a, 0x15, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x61, 0x74, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x59, 0x5a, 0x57,
	0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6f, 0x73, 0x74, 0x2e, 0x63, 0x68, 0x2f, 0x69, 0x6e,
	0x73, 0x2f, 0x6a, 0x61, 0x6c, 0x61, 0x70, 0x65, 0x6e, 0x6f, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x75, 0x73, 0x68, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70,
	0x75, 0x73, 0x68, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x70, 0x75, 0x73, 0x68,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_push_service_proto_rawDescOnce sync.Once
	file_push_service_proto_rawDescData = file_push_service_proto_rawDesc
)

func file_push_service_proto_rawDescGZIP() []byte {
	file_push_service_proto_rawDescOnce.Do(func() {
		file_push_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_push_service_proto_rawDescData)
	})
	return file_push_service_proto_rawDescData
}

var file_push_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_push_service_proto_goTypes = []interface{}{
	(*IPv4Addresses)(nil), // 0: pushservice.IPv4Addresses
	(*DataRate)(nil),      // 1: pushservice.DataRate
}
var file_push_service_proto_depIdxs = []int32{
	0, // 0: pushservice.PushService.SubscribeToDataRates:input_type -> pushservice.IPv4Addresses
	1, // 1: pushservice.PushService.SubscribeToDataRates:output_type -> pushservice.DataRate
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_push_service_proto_init() }
func file_push_service_proto_init() {
	if File_push_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_push_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPv4Addresses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_push_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_push_service_proto_goTypes,
		DependencyIndexes: file_push_service_proto_depIdxs,
		MessageInfos:      file_push_service_proto_msgTypes,
	}.Build()
	File_push_service_proto = out.File
	file_push_service_proto_rawDesc = nil
	file_push_service_proto_goTypes = nil
	file_push_service_proto_depIdxs = nil
}
