// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pushservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PushServiceClient is the client API for PushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushServiceClient interface {
	SubscribeToDataRates(ctx context.Context, in *IPv4Addresses, opts ...grpc.CallOption) (PushService_SubscribeToDataRatesClient, error)
}

type pushServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPushServiceClient(cc grpc.ClientConnInterface) PushServiceClient {
	return &pushServiceClient{cc}
}

func (c *pushServiceClient) SubscribeToDataRates(ctx context.Context, in *IPv4Addresses, opts ...grpc.CallOption) (PushService_SubscribeToDataRatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &PushService_ServiceDesc.Streams[0], "/pushservice.PushService/SubscribeToDataRates", opts...)
	if err != nil {
		return nil, err
	}
	x := &pushServiceSubscribeToDataRatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PushService_SubscribeToDataRatesClient interface {
	Recv() (*DataRate, error)
	grpc.ClientStream
}

type pushServiceSubscribeToDataRatesClient struct {
	grpc.ClientStream
}

func (x *pushServiceSubscribeToDataRatesClient) Recv() (*DataRate, error) {
	m := new(DataRate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PushServiceServer is the server API for PushService service.
// All implementations must embed UnimplementedPushServiceServer
// for forward compatibility
type PushServiceServer interface {
	SubscribeToDataRates(*IPv4Addresses, PushService_SubscribeToDataRatesServer) error
	mustEmbedUnimplementedPushServiceServer()
}

// UnimplementedPushServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPushServiceServer struct {
}

func (UnimplementedPushServiceServer) SubscribeToDataRates(*IPv4Addresses, PushService_SubscribeToDataRatesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToDataRates not implemented")
}
func (UnimplementedPushServiceServer) mustEmbedUnimplementedPushServiceServer() {}

// UnsafePushServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushServiceServer will
// result in compilation errors.
type UnsafePushServiceServer interface {
	mustEmbedUnimplementedPushServiceServer()
}

func RegisterPushServiceServer(s grpc.ServiceRegistrar, srv PushServiceServer) {
	s.RegisterService(&PushService_ServiceDesc, srv)
}

func _PushService_SubscribeToDataRates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IPv4Addresses)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PushServiceServer).SubscribeToDataRates(m, &pushServiceSubscribeToDataRatesServer{stream})
}

type PushService_SubscribeToDataRatesServer interface {
	Send(*DataRate) error
	grpc.ServerStream
}

type pushServiceSubscribeToDataRatesServer struct {
	grpc.ServerStream
}

func (x *pushServiceSubscribeToDataRatesServer) Send(m *DataRate) error {
	return x.ServerStream.SendMsg(m)
}

// PushService_ServiceDesc is the grpc.ServiceDesc for PushService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pushservice.PushService",
	HandlerType: (*PushServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToDataRates",
			Handler:       _PushService_SubscribeToDataRates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "push-service.proto",
}
