// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: requestservice.proto

package requestservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LsNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Asn      int32  `protobuf:"varint,3,opt,name=asn,proto3" json:"asn,omitempty"`
	RouterIp string `protobuf:"bytes,4,opt,name=router_ip,json=routerIp,proto3" json:"router_ip,omitempty"`
}

func (x *LsNode) Reset() {
	*x = LsNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsNode) ProtoMessage() {}

func (x *LsNode) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsNode.ProtoReflect.Descriptor instead.
func (*LsNode) Descriptor() ([]byte, []int) {
	return file_requestservice_proto_rawDescGZIP(), []int{0}
}

func (x *LsNode) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LsNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LsNode) GetAsn() int32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *LsNode) GetRouterIp() string {
	if x != nil {
		return x.RouterIp
	}
	return ""
}

type LsNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *LsNodeRequest) Reset() {
	*x = LsNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsNodeRequest) ProtoMessage() {}

func (x *LsNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsNodeRequest.ProtoReflect.Descriptor instead.
func (*LsNodeRequest) Descriptor() ([]byte, []int) {
	return file_requestservice_proto_rawDescGZIP(), []int{1}
}

func (x *LsNodeRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type LsLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key          string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RouterIp     string `protobuf:"bytes,2,opt,name=router_ip,json=routerIp,proto3" json:"router_ip,omitempty"`
	PeerIp       string `protobuf:"bytes,3,opt,name=peer_ip,json=peerIp,proto3" json:"peer_ip,omitempty"`
	LocalLinkIp  string `protobuf:"bytes,4,opt,name=localLink_ip,json=localLinkIp,proto3" json:"localLink_ip,omitempty"`
	RemoteLinkIp string `protobuf:"bytes,5,opt,name=remoteLink_ip,json=remoteLinkIp,proto3" json:"remoteLink_ip,omitempty"`
	IgpMetric    int32  `protobuf:"varint,6,opt,name=igp_metric,json=igpMetric,proto3" json:"igp_metric,omitempty"`
}

func (x *LsLink) Reset() {
	*x = LsLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsLink) ProtoMessage() {}

func (x *LsLink) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsLink.ProtoReflect.Descriptor instead.
func (*LsLink) Descriptor() ([]byte, []int) {
	return file_requestservice_proto_rawDescGZIP(), []int{2}
}

func (x *LsLink) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LsLink) GetRouterIp() string {
	if x != nil {
		return x.RouterIp
	}
	return ""
}

func (x *LsLink) GetPeerIp() string {
	if x != nil {
		return x.PeerIp
	}
	return ""
}

func (x *LsLink) GetLocalLinkIp() string {
	if x != nil {
		return x.LocalLinkIp
	}
	return ""
}

func (x *LsLink) GetRemoteLinkIp() string {
	if x != nil {
		return x.RemoteLinkIp
	}
	return ""
}

func (x *LsLink) GetIgpMetric() int32 {
	if x != nil {
		return x.IgpMetric
	}
	return 0
}

type LsLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *LsLinkRequest) Reset() {
	*x = LsLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsLinkRequest) ProtoMessage() {}

func (x *LsLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsLinkRequest.ProtoReflect.Descriptor instead.
func (*LsLinkRequest) Descriptor() ([]byte, []int) {
	return file_requestservice_proto_rawDescGZIP(), []int{3}
}

func (x *LsLinkRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type DataRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ipv4Address string `protobuf:"bytes,1,opt,name=ipv4address,proto3" json:"ipv4address,omitempty"`
	DataRate    int64  `protobuf:"varint,2,opt,name=dataRate,proto3" json:"dataRate,omitempty"`
}

func (x *DataRate) Reset() {
	*x = DataRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRate) ProtoMessage() {}

func (x *DataRate) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRate.ProtoReflect.Descriptor instead.
func (*DataRate) Descriptor() ([]byte, []int) {
	return file_requestservice_proto_rawDescGZIP(), []int{4}
}

func (x *DataRate) GetIpv4Address() string {
	if x != nil {
		return x.Ipv4Address
	}
	return ""
}

func (x *DataRate) GetDataRate() int64 {
	if x != nil {
		return x.DataRate
	}
	return 0
}

type DataRateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ipv4Addresses []string `protobuf:"bytes,1,rep,name=ipv4addresses,proto3" json:"ipv4addresses,omitempty"`
}

func (x *DataRateRequest) Reset() {
	*x = DataRateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_requestservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRateRequest) ProtoMessage() {}

func (x *DataRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_requestservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRateRequest.ProtoReflect.Descriptor instead.
func (*DataRateRequest) Descriptor() ([]byte, []int) {
	return file_requestservice_proto_rawDescGZIP(), []int{5}
}

func (x *DataRateRequest) GetIpv4Addresses() []string {
	if x != nil {
		return x.Ipv4Addresses
	}
	return nil
}

var File_requestservice_proto protoreflect.FileDescriptor

var file_requestservice_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x5d, 0x0a, 0x06, 0x4c, 0x73, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x73, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x73, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x5f, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x49, 0x70, 0x22, 0x23, 0x0a, 0x0d, 0x4c, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0xb7, 0x01, 0x0a, 0x06, 0x4c,
	0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x49, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x70, 0x12, 0x21, 0x0a,
	0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x5f, 0x69, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x49, 0x70,
	0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x5f, 0x69,
	0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x4c,
	0x69, 0x6e, 0x6b, 0x49, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x67, 0x70, 0x5f, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x67, 0x70, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x22, 0x23, 0x0a, 0x0d, 0x4c, 0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x48, 0x0a, 0x08, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x70, 0x76, 0x34, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x70, 0x76, 0x34,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x61, 0x74, 0x65, 0x22, 0x37, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x52, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x70, 0x76, 0x34, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x69,
	0x70, 0x76, 0x34, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x32, 0xed, 0x01, 0x0a,
	0x0a, 0x41, 0x70, 0x69, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x47, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x4c, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x73, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x73, 0x4e, 0x6f, 0x64, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x47, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x73, 0x4c, 0x69, 0x6e,
	0x6b, 0x73, 0x12, 0x1d, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x4c, 0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x4c, 0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x12, 0x4d, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1f, 0x2e,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x61, 0x74, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x3c, 0x5a, 0x3a,
	0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6f, 0x73, 0x74, 0x2e, 0x63, 0x68, 0x2f, 0x69, 0x6e,
	0x73, 0x2f, 0x6a, 0x61, 0x6c, 0x61, 0x70, 0x65, 0x6e, 0x6f, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x72, 0x2d, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_requestservice_proto_rawDescOnce sync.Once
	file_requestservice_proto_rawDescData = file_requestservice_proto_rawDesc
)

func file_requestservice_proto_rawDescGZIP() []byte {
	file_requestservice_proto_rawDescOnce.Do(func() {
		file_requestservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_requestservice_proto_rawDescData)
	})
	return file_requestservice_proto_rawDescData
}

var file_requestservice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_requestservice_proto_goTypes = []interface{}{
	(*LsNode)(nil),          // 0: requestservice.LsNode
	(*LsNodeRequest)(nil),   // 1: requestservice.LsNodeRequest
	(*LsLink)(nil),          // 2: requestservice.LsLink
	(*LsLinkRequest)(nil),   // 3: requestservice.LsLinkRequest
	(*DataRate)(nil),        // 4: requestservice.DataRate
	(*DataRateRequest)(nil), // 5: requestservice.DataRateRequest
}
var file_requestservice_proto_depIdxs = []int32{
	1, // 0: requestservice.ApiGateway.GetLsNodes:input_type -> requestservice.LsNodeRequest
	3, // 1: requestservice.ApiGateway.GetLsLinks:input_type -> requestservice.LsLinkRequest
	5, // 2: requestservice.ApiGateway.GetDataRates:input_type -> requestservice.DataRateRequest
	0, // 3: requestservice.ApiGateway.GetLsNodes:output_type -> requestservice.LsNode
	2, // 4: requestservice.ApiGateway.GetLsLinks:output_type -> requestservice.LsLink
	4, // 5: requestservice.ApiGateway.GetDataRates:output_type -> requestservice.DataRate
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_requestservice_proto_init() }
func file_requestservice_proto_init() {
	if File_requestservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_requestservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_requestservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_requestservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_requestservice_proto_goTypes,
		DependencyIndexes: file_requestservice_proto_depIdxs,
		MessageInfos:      file_requestservice_proto_msgTypes,
	}.Build()
	File_requestservice_proto = out.File
	file_requestservice_proto_rawDesc = nil
	file_requestservice_proto_goTypes = nil
	file_requestservice_proto_depIdxs = nil
}
