// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package requestservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RequestServiceClient is the client API for RequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RequestServiceClient interface {
	GetLSNodes(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*LSNodeResponse, error)
	GetLSLinks(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*LSLinkResponse, error)
	GetLSPrefixes(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*LSPrefixResponse, error)
	GetLSSRv6SIDs(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*LSSRv6SIDResponse, error)
	GetTelemetryData(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (*TelemetryResponse, error)
}

type requestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRequestServiceClient(cc grpc.ClientConnInterface) RequestServiceClient {
	return &requestServiceClient{cc}
}

func (c *requestServiceClient) GetLSNodes(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*LSNodeResponse, error) {
	out := new(LSNodeResponse)
	err := c.cc.Invoke(ctx, "/requestservice.RequestService/GetLSNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestServiceClient) GetLSLinks(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*LSLinkResponse, error) {
	out := new(LSLinkResponse)
	err := c.cc.Invoke(ctx, "/requestservice.RequestService/GetLSLinks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestServiceClient) GetLSPrefixes(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*LSPrefixResponse, error) {
	out := new(LSPrefixResponse)
	err := c.cc.Invoke(ctx, "/requestservice.RequestService/GetLSPrefixes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestServiceClient) GetLSSRv6SIDs(ctx context.Context, in *TopologyRequest, opts ...grpc.CallOption) (*LSSRv6SIDResponse, error) {
	out := new(LSSRv6SIDResponse)
	err := c.cc.Invoke(ctx, "/requestservice.RequestService/GetLSSRv6SIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestServiceClient) GetTelemetryData(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (*TelemetryResponse, error) {
	out := new(TelemetryResponse)
	err := c.cc.Invoke(ctx, "/requestservice.RequestService/GetTelemetryData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequestServiceServer is the server API for RequestService service.
// All implementations must embed UnimplementedRequestServiceServer
// for forward compatibility
type RequestServiceServer interface {
	GetLSNodes(context.Context, *TopologyRequest) (*LSNodeResponse, error)
	GetLSLinks(context.Context, *TopologyRequest) (*LSLinkResponse, error)
	GetLSPrefixes(context.Context, *TopologyRequest) (*LSPrefixResponse, error)
	GetLSSRv6SIDs(context.Context, *TopologyRequest) (*LSSRv6SIDResponse, error)
	GetTelemetryData(context.Context, *TelemetryRequest) (*TelemetryResponse, error)
	mustEmbedUnimplementedRequestServiceServer()
}

// UnimplementedRequestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRequestServiceServer struct {
}

func (UnimplementedRequestServiceServer) GetLSNodes(context.Context, *TopologyRequest) (*LSNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLSNodes not implemented")
}
func (UnimplementedRequestServiceServer) GetLSLinks(context.Context, *TopologyRequest) (*LSLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLSLinks not implemented")
}
func (UnimplementedRequestServiceServer) GetLSPrefixes(context.Context, *TopologyRequest) (*LSPrefixResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLSPrefixes not implemented")
}
func (UnimplementedRequestServiceServer) GetLSSRv6SIDs(context.Context, *TopologyRequest) (*LSSRv6SIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLSSRv6SIDs not implemented")
}
func (UnimplementedRequestServiceServer) GetTelemetryData(context.Context, *TelemetryRequest) (*TelemetryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTelemetryData not implemented")
}
func (UnimplementedRequestServiceServer) mustEmbedUnimplementedRequestServiceServer() {}

// UnsafeRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequestServiceServer will
// result in compilation errors.
type UnsafeRequestServiceServer interface {
	mustEmbedUnimplementedRequestServiceServer()
}

func RegisterRequestServiceServer(s grpc.ServiceRegistrar, srv RequestServiceServer) {
	s.RegisterService(&RequestService_ServiceDesc, srv)
}

func _RequestService_GetLSNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestServiceServer).GetLSNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/requestservice.RequestService/GetLSNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestServiceServer).GetLSNodes(ctx, req.(*TopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestService_GetLSLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestServiceServer).GetLSLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/requestservice.RequestService/GetLSLinks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestServiceServer).GetLSLinks(ctx, req.(*TopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestService_GetLSPrefixes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestServiceServer).GetLSPrefixes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/requestservice.RequestService/GetLSPrefixes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestServiceServer).GetLSPrefixes(ctx, req.(*TopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestService_GetLSSRv6SIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestServiceServer).GetLSSRv6SIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/requestservice.RequestService/GetLSSRv6SIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestServiceServer).GetLSSRv6SIDs(ctx, req.(*TopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestService_GetTelemetryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestServiceServer).GetTelemetryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/requestservice.RequestService/GetTelemetryData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestServiceServer).GetTelemetryData(ctx, req.(*TelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RequestService_ServiceDesc is the grpc.ServiceDesc for RequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "requestservice.RequestService",
	HandlerType: (*RequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLSNodes",
			Handler:    _RequestService_GetLSNodes_Handler,
		},
		{
			MethodName: "GetLSLinks",
			Handler:    _RequestService_GetLSLinks_Handler,
		},
		{
			MethodName: "GetLSPrefixes",
			Handler:    _RequestService_GetLSPrefixes_Handler,
		},
		{
			MethodName: "GetLSSRv6SIDs",
			Handler:    _RequestService_GetLSSRv6SIDs_Handler,
		},
		{
			MethodName: "GetTelemetryData",
			Handler:    _RequestService_GetTelemetryData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "requestservice.proto",
}
