// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request-service.proto

package requestservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Nodes struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nodes) Reset()         { *m = Nodes{} }
func (m *Nodes) String() string { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()    {}
func (*Nodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_4000569de199abc4, []int{0}
}

func (m *Nodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nodes.Unmarshal(m, b)
}
func (m *Nodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nodes.Marshal(b, m, deterministic)
}
func (m *Nodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nodes.Merge(m, src)
}
func (m *Nodes) XXX_Size() int {
	return xxx_messageInfo_Nodes.Size(m)
}
func (m *Nodes) XXX_DiscardUnknown() {
	xxx_messageInfo_Nodes.DiscardUnknown(m)
}

var xxx_messageInfo_Nodes proto.InternalMessageInfo

func (m *Nodes) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Node struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Asn                  int32    `protobuf:"varint,3,opt,name=asn,proto3" json:"asn,omitempty"`
	RouterIp             string   `protobuf:"bytes,4,opt,name=router_ip,json=routerIp,proto3" json:"router_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_4000569de199abc4, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetAsn() int32 {
	if m != nil {
		return m.Asn
	}
	return 0
}

func (m *Node) GetRouterIp() string {
	if m != nil {
		return m.RouterIp
	}
	return ""
}

type NodeIds struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeIds) Reset()         { *m = NodeIds{} }
func (m *NodeIds) String() string { return proto.CompactTextString(m) }
func (*NodeIds) ProtoMessage()    {}
func (*NodeIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_4000569de199abc4, []int{2}
}

func (m *NodeIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeIds.Unmarshal(m, b)
}
func (m *NodeIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeIds.Marshal(b, m, deterministic)
}
func (m *NodeIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeIds.Merge(m, src)
}
func (m *NodeIds) XXX_Size() int {
	return xxx_messageInfo_NodeIds.Size(m)
}
func (m *NodeIds) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeIds.DiscardUnknown(m)
}

var xxx_messageInfo_NodeIds proto.InternalMessageInfo

func (m *NodeIds) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type IPv4Addresses struct {
	Ipv4Address          []string `protobuf:"bytes,1,rep,name=ipv4address,proto3" json:"ipv4address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPv4Addresses) Reset()         { *m = IPv4Addresses{} }
func (m *IPv4Addresses) String() string { return proto.CompactTextString(m) }
func (*IPv4Addresses) ProtoMessage()    {}
func (*IPv4Addresses) Descriptor() ([]byte, []int) {
	return fileDescriptor_4000569de199abc4, []int{3}
}

func (m *IPv4Addresses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPv4Addresses.Unmarshal(m, b)
}
func (m *IPv4Addresses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPv4Addresses.Marshal(b, m, deterministic)
}
func (m *IPv4Addresses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPv4Addresses.Merge(m, src)
}
func (m *IPv4Addresses) XXX_Size() int {
	return xxx_messageInfo_IPv4Addresses.Size(m)
}
func (m *IPv4Addresses) XXX_DiscardUnknown() {
	xxx_messageInfo_IPv4Addresses.DiscardUnknown(m)
}

var xxx_messageInfo_IPv4Addresses proto.InternalMessageInfo

func (m *IPv4Addresses) GetIpv4Address() []string {
	if m != nil {
		return m.Ipv4Address
	}
	return nil
}

type DataRate struct {
	DataRate             int64    `protobuf:"varint,1,opt,name=dataRate,proto3" json:"dataRate,omitempty"`
	Ipv4Address          string   `protobuf:"bytes,2,opt,name=ipv4address,proto3" json:"ipv4address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRate) Reset()         { *m = DataRate{} }
func (m *DataRate) String() string { return proto.CompactTextString(m) }
func (*DataRate) ProtoMessage()    {}
func (*DataRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_4000569de199abc4, []int{4}
}

func (m *DataRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRate.Unmarshal(m, b)
}
func (m *DataRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRate.Marshal(b, m, deterministic)
}
func (m *DataRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRate.Merge(m, src)
}
func (m *DataRate) XXX_Size() int {
	return xxx_messageInfo_DataRate.Size(m)
}
func (m *DataRate) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRate.DiscardUnknown(m)
}

var xxx_messageInfo_DataRate proto.InternalMessageInfo

func (m *DataRate) GetDataRate() int64 {
	if m != nil {
		return m.DataRate
	}
	return 0
}

func (m *DataRate) GetIpv4Address() string {
	if m != nil {
		return m.Ipv4Address
	}
	return ""
}

func init() {
	proto.RegisterType((*Nodes)(nil), "requestservice.Nodes")
	proto.RegisterType((*Node)(nil), "requestservice.Node")
	proto.RegisterType((*NodeIds)(nil), "requestservice.NodeIds")
	proto.RegisterType((*IPv4Addresses)(nil), "requestservice.IPv4Addresses")
	proto.RegisterType((*DataRate)(nil), "requestservice.DataRate")
}

func init() { proto.RegisterFile("request-service.proto", fileDescriptor_4000569de199abc4) }

var fileDescriptor_4000569de199abc4 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x4f, 0xea, 0x40,
	0x14, 0x85, 0xe9, 0x2b, 0x3c, 0xca, 0xe5, 0xbd, 0x97, 0x97, 0x89, 0xc4, 0x06, 0x62, 0xd2, 0x74,
	0x45, 0x4c, 0x68, 0x15, 0x58, 0x89, 0x2e, 0x30, 0x26, 0xd8, 0x98, 0x18, 0xd3, 0xa5, 0x2e, 0xcc,
	0x40, 0x6f, 0x74, 0x14, 0xdb, 0xb1, 0x77, 0xc0, 0xf0, 0x43, 0xfd, 0x3f, 0x66, 0xa6, 0xc5, 0x00,
	0xc1, 0xdd, 0x99, 0x6f, 0xce, 0x39, 0x99, 0x7b, 0x5b, 0x68, 0xe5, 0xf8, 0xbe, 0x40, 0x52, 0x3d,
	0xc2, 0x7c, 0x29, 0x66, 0x18, 0xc8, 0x3c, 0x53, 0x19, 0xfb, 0x57, 0xe2, 0x92, 0xfa, 0x03, 0xa8,
	0xdd, 0x66, 0x09, 0x12, 0x3b, 0x86, 0x5a, 0xaa, 0x85, 0x6b, 0x79, 0x76, 0xb7, 0xd9, 0x3f, 0x08,
	0xb6, 0x8d, 0x81, 0x76, 0xc5, 0x85, 0xc5, 0x7f, 0x80, 0xaa, 0x3e, 0xb2, 0xff, 0x60, 0xbf, 0xe2,
	0xca, 0xb5, 0x3c, 0xab, 0xdb, 0x88, 0xb5, 0x64, 0x0c, 0xaa, 0x29, 0x7f, 0x43, 0xf7, 0x97, 0x41,
	0x46, 0x6b, 0x17, 0xa7, 0xd4, 0xb5, 0x3d, 0xab, 0x5b, 0x8b, 0xb5, 0x64, 0x1d, 0x68, 0xe4, 0xd9,
	0x42, 0x61, 0xfe, 0x28, 0xa4, 0x5b, 0x35, 0x56, 0xa7, 0x00, 0x91, 0xf4, 0x3b, 0x50, 0xd7, 0xe5,
	0x51, 0x42, 0x3a, 0x29, 0x92, 0xe2, 0x45, 0x8d, 0x58, 0x4b, 0xff, 0x14, 0xfe, 0x46, 0x77, 0xcb,
	0xe1, 0x38, 0x49, 0x72, 0x24, 0x42, 0x62, 0x1e, 0x34, 0x85, 0x5c, 0x0e, 0x79, 0x01, 0x4a, 0xeb,
	0x26, 0xf2, 0xaf, 0xc1, 0xb9, 0xe2, 0x8a, 0xc7, 0x5c, 0x21, 0x6b, 0x83, 0x93, 0x94, 0xda, 0xbc,
	0xda, 0x8e, 0xbf, 0xcf, 0xbb, 0x4d, 0xc5, 0x04, 0x9b, 0xa8, 0xff, 0x69, 0x01, 0x8c, 0xa5, 0x98,
	0x70, 0x85, 0x1f, 0x7c, 0xc5, 0x46, 0x50, 0x9f, 0xa0, 0x32, 0x8b, 0x38, 0xdc, 0xb7, 0xad, 0x28,
	0xa1, 0x76, 0x6b, 0xdf, 0x05, 0xf9, 0x15, 0x76, 0x01, 0x4e, 0x19, 0xa6, 0x9f, 0xd3, 0x7b, 0x3f,
	0x82, 0x5f, 0x39, 0xb1, 0xd8, 0x0d, 0xfc, 0x99, 0xa0, 0x5a, 0xcf, 0x45, 0xec, 0x68, 0xd7, 0xb9,
	0xb5, 0xa5, 0xb6, 0xbb, 0x7b, 0xbd, 0x4e, 0xea, 0xb2, 0xcb, 0xf3, 0xfb, 0xb3, 0x27, 0xa1, 0xe6,
	0x7c, 0x1a, 0x64, 0xa4, 0x82, 0xd9, 0x73, 0x28, 0x52, 0x0a, 0x5f, 0xf8, 0x9c, 0x4b, 0x4c, 0xb3,
	0x1e, 0x97, 0x22, 0xa4, 0xbc, 0xc7, 0xa5, 0x0c, 0xcd, 0x2f, 0x34, 0xda, 0xae, 0x9a, 0xfe, 0x36,
	0x74, 0xf0, 0x15, 0x00, 0x00, 0xff, 0xff, 0x96, 0xd1, 0x63, 0x71, 0x71, 0x02, 0x00, 0x00,
}
