name: JAGW Pipieline

on:
  workflow_dispatch:
    inputs:
      tag_name:   
        required: true
        type: string
      build_branch:
        description: "Build branch (dev | main)"
        required: true
        type: string
      type:
        description: "Type (dev | release)"
        required: true
        type: string

jobs:
  call-update-dependencies:
    uses: jalapeno-api-gateway/demo-sr-app/.github/workflows/update-dependencies.yml@dev
    with:
      tag_name: ${{ github.event.inputs.tag_name }}
  call-merge-to-main:
    needs: call-update-dependencies
    if: github.event.inputs.type == 'release'
    uses: jalapeno-api-gateway/demo-sr-app/.github/workflows/merge-to-main.yml@dev
  call-create-tag:
    needs: [call-merge-to-main]
    uses: jalapeno-api-gateway/demo-sr-app/.github/workflows/create-tag.yml@dev   
    if: |
      always() &&
      (needs.call-merge-to-main.result == 'success' || needs.call-merge-to-main.result == 'skipped') &&
      needs.call-update-dependencies.result == 'success'
    with:
      branch: ${{ github.event.inputs.build_branch }}
      tag_name: ${{ github.event.inputs.tag_name }}
  call-create-release:
    needs: [call-create-tag]
    uses: jalapeno-api-gateway/demo-sr-app/.github/workflows/create-release.yml@dev
    if: |
      always() &&
      (needs.call-merge-to-main.result == 'success' || needs.call-merge-to-main.result == 'skipped') &&
      needs.call-create-tag.result == 'success' &&
      needs.call-update-dependencies.result == 'success'
    with:
      tag_name: ${{ github.event.inputs.tag_name }}
